
import { DESIGN_HOMEPAGE, USER_MANAGEMENT, CATEGORY_MANAGEMENT, TOPIC_MANAGEMENT, PERMISSION_MANAGEMENT, QUOTE_MANAGEMENT, GROUP_MANAGEMENT,EDITOR_PICK, ARTICLE_CREATE } from './MODULES';
import {default as COLORS} from './COLORS';
const	NAME='ScoopWhoop';
const SITE = 'http://10.2.1.14:8095';
const API={
		prefix:'http://10.2.1.14:8095/swadmin',
		suffix:'/api/v2'
	}
const INTELLI_API = {
		prefix: 'https://intelli.scoopwhoop.com',
	}	
const MODULES={
    ARTICLE_CREATE,
	DESIGN_HOMEPAGE,
	USER_MANAGEMENT,
	CATEGORY_MANAGEMENT,
	TOPIC_MANAGEMENT, 
	PERMISSION_MANAGEMENT,
	QUOTE_MANAGEMENT,
	GROUP_MANAGEMENT,
	EDITOR_PICK
}
export { NAME, API, INTELLI_API, MODULES, COLORS, SITE };
