module.exports={
	
	ARTICLE_CREATE:{
		title:'Create Article',
		permission:'article_edit',
		active:true,
		uri:'/article/new'
	},
	DESIGN_HOMEPAGE:{
		title:'Design Homepage',
		permission:'home_design',
		active:true,
		uri:'/homedesign'
		// uri:'/homepage',
		// submodules:{
		// 	'primary-masthead':{
		// 		title:'Primary Masthead',
		// 		permission:'custom_masthead',
		// 		uri:'/primary-masthead',
		// 		dataKey:'primary_masthead'
		// 	},
		// 	'detailed-card':{

		// 		title:'Masthead 1 (Detailed Card)',
		// 		permission:'custom_masthead',
		// 		uri:'/detailed-card',
		// 		dataKey:'detailed_card'
		// 	},
		// 	'vertical-card':{
		// 		title:'Masthead 1 (Vertical Card)',
		// 		permission:'custom_masthead',
		// 		uri:'/vertical-card',
		// 		dataKey:'vertical_card'
		// 	},
		// 	'brand-article':{
		// 		title:'Secondary Masthead (Brand Article)',
		// 		permission:'custom_brand',
		// 		uri:'/secondary-masthead',
		// 		dataKey:'brand_article'
		// 	},
		// 	trending: {
		// 		title:'Trending',
		// 		permission:'trending',
		// 		uri:'/trending',
		// 		dataKey:'trending'
		// 	},
		// 	video:{
		// 		title:'Video',
		// 		permission:'custom_video',
		// 		uri:'/video',
		// 		dataKey:'video'
				
		// 	},
		// }
	},
	CATEGORY_MANAGEMENT:{
		title:'Category Management',
		permission:'category_view',
		active:true,
		uri:'/categories'
	},
	USER_MANAGEMENT:{
		title:'User management',
		permission:'user_view',
		active:true,
		uri:'/users'
	},
	TOPIC_MANAGEMENT:{
		title:'Topic management',
		permission:'topic_view',
		active:true,
		uri:'/topics'
	},
	PERMISSION_MANAGEMENT:{
		title:'Permission management',
		permission:'perm_view',
		active:true,
		uri:'/permissions'
	},
	QUOTE_MANAGEMENT:{
		title:'Quote management',
		permission:'create_quotes',
		active:true,
		uri:'/quotes'
	},
	GROUP_MANAGEMENT:{
		title:'Group management',
		permission:'perm_view',
		active:true,
		uri:'/groups'
	},
	EDITOR_PICK:{
		title:'Editor Pick',
		permission:'create_edt_pick',
		active:true,
		uri:'/editorPick'
	}
	// ,{
	// 	title:'Topic Management',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Group Management',
	// 	permission:'',
	// 	active:false
	// },

	// {
	// 	title:'Mailchimp',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Mailchimp Report',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Push Notifications',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Quotes management',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Banner management',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Design Category Page',
	// 	permission:'',
	// 	active:false
	// },
	// {
	// 	title:'Live Blog',
	// 	permission:'',
	// 	active:false
	// },

}