module.exports={
	LASTWORKEDON: '/last_worked_on/',
    PUBLISHED: '/published_articles/',
    DRAFTS: '/user_drafts/',
    INVALIDATED: '/user_invalidated_articles/',
    CREATENEW: '/create_new/',
    PASTLENS: '/pastlens_raw',
    PROJECTIONS: '/projections_raw',
    PROMOTE: '/promote_raw',
    LATEST: '/latest_raw',
    SCORECARD: '/scorecard_raw',
    YOUTUBEALERT: '/youtube_alert',
    TWITTERALERT: '/twitter_alert',
    QUOTESALERT: '/quotes_alert',
    CREATEDASHBAORD: '/create_dashboard/',
    GETDASHBOARD: '/get_dashboard/',
    EDITDASHBAORD: '/edit_dashboard/',
    INVALIDATEDASHBAORD: '/invalidate_dashboard/',
}